package com.spring.email.template;

import org.springframework.stereotype.Component;
import com.spring.entities.UserDetails;

@Component
public class DatfuslabWelcome {
    
    public String getTemplate(UserDetails userDetails) {
        
        String template = "<!DOCTYPE html>\r\n"
        		+ "<html>\r\n"
        		+ "\r\n"
        		+ "<head>\r\n"
        		+ "  <meta charset=\"UTF-8\">\r\n"
        		+ "  <title>Welcome to MyDonation</title>\r\n"
        		+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n"
        		+ "</head>\r\n"
        		+ "\r\n"
        		+ "<body style=\"margin:0; padding:0; background:#f7f7f7; font-family:Arial, sans-serif;\">\r\n"
        		+ "\r\n"
        		+ "  <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"padding:30px 0;\">\r\n"
        		+ "    <tr>\r\n"
        		+ "      <td align=\"center\">\r\n"
        		+ "\r\n"
        		+ "        <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background:#ffffff; border-radius:8px; overflow:hidden;\">\r\n"
        		+ "\r\n"
        		+ "          <!-- Header -->\r\n"
        		+ "          <tr>\r\n"
        		+ "            <td style=\"background:#ff7a00; padding:25px; text-align:center;\">\r\n"
        		+ "              <h1 style=\"color:#ffffff; margin:0; font-size:28px;\">Welcome to MyDonation 🤝</h1>\r\n"
        		+ "            </td>\r\n"
        		+ "          </tr>\r\n"
        		+ "\r\n"
        		+ "          <!-- Banner -->\r\n"
        		+ "          <tr>\r\n"
        		+ "            <td style=\"padding:20px; text-align:center;\">\r\n"
        		+ "              <img src=\"https://via.placeholder.com/550x200/ff7a00/ffffff?text=Welcome+to+MyDonation\"\r\n"
        		+ "                   alt=\"MyDonation Banner\"\r\n"
        		+ "                   style=\"width:100%; max-width:550px; border-radius:6px;\">\r\n"
        		+ "            </td>\r\n"
        		+ "          </tr>\r\n"
        		+ "\r\n"
        		+ "          <!-- Body Content -->\r\n"
        		+ "          <tr>\r\n"
        		+ "            <td style=\"padding:25px;\">\r\n"
        		+ "              <h2 style=\"color:#ff7a00; margin-top:0; font-size:22px;\">Hello Vivek Bharti,</h2>\r\n"
        		+ "\r\n"
        		+ "              <p style=\"font-size:15px; color:#444; line-height:1.6; margin:15px 0;\">\r\n"
        		+ "                Thank you for joining <strong>MyDonation</strong> — a powerful and easy-to-use donation management platform built to support NGOs like yours.\r\n"
        		+ "                We’re excited to welcome you on board!\r\n"
        		+ "              </p>\r\n"
        		+ "\r\n"
        		+ "              <p style=\"font-size:15px; color:#444; line-height:1.6;\">\r\n"
        		+ "                With MyDonation, your NGO can:\r\n"
        		+ "              </p>\r\n"
        		+ "\r\n"
        		+ "              <!-- NGO Modules -->\r\n"
        		+ "              <div style=\"background:#fff3e5; padding:20px; border-radius:6px; border-left:5px solid #ff7a00; margin:20px 0;\">\r\n"
        		+ "                <h3 style=\"margin-top:0; color:#ff7a00;\">🧩 NGO Modules You Get</h3>\r\n"
        		+ "\r\n"
        		+ "                <ul style=\"font-size:15px; color:#444; line-height:1.8; padding-left:20px; margin:0;\">\r\n"
        		+ "                  <li><strong>Donation Management</strong> – Track every donation with receipt, donor details & transaction history.</li>\r\n"
        		+ "                  <li><strong>Campaign & Causes</strong> – Create fundraising campaigns with images, videos & progress tracking.</li>\r\n"
        		+ "                  <li><strong>Donor CRM</strong> – Manage all donors, send updates, reminders & personalized messages.</li>\r\n"
        		+ "                  <li><strong>Automated Receipts</strong> – Auto-generate receipts with payment details & email delivery.</li>\r\n"
        		+ "                  <li><strong>Impact Stories Module</strong> – Publish success stories & updates to build donor trust.</li>\r\n"
        		+ "                  <li><strong>Payment Link Generator</strong> – Create custom donation links for WhatsApp, social media & SMS.</li>\r\n"
        		+ "                  <li><strong>Analytics Dashboard</strong> – See donations, campaigns, and donor growth with visual charts.</li>\r\n"
        		+ "                  <li><strong>Team & Role Management</strong> – Add staff, assign permissions, and control who can access what.</li>\r\n"
        		+ "                  <li><strong>Document & Compliance</strong> – Upload FCRA, 80G, 12A certificates and share instantly with donors.</li>\r\n"
        		+ "                </ul>\r\n"
        		+ "              </div>\r\n"
        		+ "\r\n"
        		+ "              <!-- CTA Button -->\r\n"
        		+ "              <div style=\"text-align:center; margin:25px 0;\">\r\n"
        		+ "                <a href=\"{LOGIN_URL}\"\r\n"
        		+ "                   style=\"background:#ff7a00; color:#fff; padding:12px 22px; text-decoration:none; font-size:16px;\r\n"
        		+ "                          border-radius:6px; display:inline-block;\">\r\n"
        		+ "                  Go to MyDonation Dashboard\r\n"
        		+ "                </a>\r\n"
        		+ "              </div>\r\n"
        		+ "\r\n"
        		+ "              <p style=\"font-size:15px; color:#444; line-height:1.6;\">\r\n"
        		+ "                Our team is always here to assist you.  \r\n"
        		+ "                Reach out to us at <strong style=\"color:#ff7a00;\">support@mydonation.org</strong> for any help.\r\n"
        		+ "              </p>\r\n"
        		+ "            </td>\r\n"
        		+ "          </tr>\r\n"
        		+ "\r\n"
        		+ "          <!-- Footer -->\r\n"
        		+ "          <tr>\r\n"
        		+ "            <td style=\"background:#f1f1f1; padding:20px; text-align:center;\">\r\n"
        		+ "              <p style=\"margin:0; font-size:13px; color:#888;\">\r\n"
        		+ "                © 2025 MyDonation • All Rights Reserved\r\n"
        		+ "              </p>\r\n"
        		+ "            </td>\r\n"
        		+ "          </tr>\r\n"
        		+ "\r\n"
        		+ "        </table>\r\n"
        		+ "\r\n"
        		+ "      </td>\r\n"
        		+ "    </tr>\r\n"
        		+ "  </table>\r\n"
        		+ "\r\n"
        		+ "</body>\r\n"
        		+ "\r\n"
        		+ "</html>\r\n"
        		+ "";
        
        return template;
    }
}
